#!/usr/bin/env bash

set -eo pipefail

function banner {
  echo ""
  echo "███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ "
  echo "██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗"
  echo "███████╗██║   ██║██╔██╗ ██║███████║██████╔╝"
  echo "╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗"
  echo "███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║"
  echo "╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝"
  echo ""
}

function task:lint {
  php vendor/bin/ecs check ${*}
}

function task:test {
  php vendor/bin/phpunit tests/ ${*}
}

banner
"task:${@:-help}"